from admin_commands import *
new_player("john", "smith", "john.smith@gmail.com", "203-555-5555")
new_player("bob", "smith", "bob.smith@gmail.com", "203-567-5555")
new_player("kenny", "smith", "kenny.smith@gmail.com", "203-555-5555")
new_player("rob", "smith", "rob.smith@gmail.com", "203-567-5555")
check_in("john.smith@gmail.com")
check_in("bob.smith@gmail.com")
check_in("kenny.smith@gmail.com")
check_in("rob.smith@gmail.com")
player_list = quick_tournament("test tournament","7/10/2024")
pair_up(round = 1,tournament_id = 1,player_list = player_list)
print_pairings(round_num = 1,tournament = 1)
#display_unfinished()
#report_match(2,0,0,1)
#increment_round(1)
#display_current_matches()
#crown_winner(1,1)
