from admin_commands import *
new_player("fake", "player", "fake.player@gmail.com", "000-000-0000")
new_player("john", "brown", "john.brown@gmail.com", "203-555-5555")
new_player("bob", "brown", "bob.brown@gmail.com", "203-567-5555")
new_player("kenny", "brown", "kenny.brown@gmail.com", "203-555-5555")
new_player("rob", "brown", "rob.brown@gmail.com", "203-567-5555")
new_player("john", "smith", "john.smith@gmail.com", "203-555-5555")
new_player("bob", "smith", "bob.smith@gmail.com", "203-567-5555")
new_player("kenny", "smith", "kenny.smith@gmail.com", "203-555-5555")
new_player("rob", "smith", "rob.smith@gmail.com", "203-567-5555")
check_in("john.smith@gmail.com")
check_in("bob.smith@gmail.com")
check_in("kenny.smith@gmail.com")
check_in("rob.smith@gmail.com")
check_in("john.brown@gmail.com")
check_in("bob.brown@gmail.com")
check_in("kenny.brown@gmail.com")
check_in("rob.brown@gmail.com")
players = quick_tournament_round_robin("test tournament","7/10/2024")
quick_tournament_bracket("test tournament","7/10/2024")
#pair_up(round_num = 1,tournament_id = 1,seeded_player_list = players)
#print_pairings(round_num = 1,tournament = 1)
#print_pairings(round_num = 2,tournament = 1)
#print_pairings(round_num = 3,tournament = 1)
#display_unfinished()
#report_match(2,0,0,1)
#increment_round(1)
#display_current_matches()
#crown_winner(1,1)9
